#!/bin/bash
set -euo pipefail

# Verifica se existe alguma tag
if git describe --tags --abbrev=0 >/dev/null 2>&1; then
  LAST_TAG=$(git describe --tags --abbrev=0)
else
  LAST_TAG=""
fi

echo "Última tag: ${LAST_TAG:-<nenhuma>}"

# Nova versão
if [[ -z "$LAST_TAG" ]]; then
  NEW_VERSION="v0.0.1"
else
  IFS='.' read -r MAJOR MINOR PATCH <<<"${LAST_TAG#v}"
  NEW_VERSION="v$MAJOR.$MINOR.$((PATCH + 1))"
fi

echo "Nova versão: $NEW_VERSION"

# Gera changelog
echo "Gerando changelog para $NEW_VERSION"
{
  echo "## $NEW_VERSION - $(date +%Y-%m-%d)"
  if [[ -n "$LAST_TAG" ]]; then
    git log "$LAST_TAG"..HEAD --pretty=format:"- %s"
  else
    git log --pretty=format:"- %s"
  fi
  echo ""
} >> CHANGELOG.md

# Git config
git config user.name "github-actions"
git config user.email "actions@github.com"

# Commit e tag
git add CHANGELOG.md

if git diff --cached --quiet; then
  echo "Nenhuma mudança no changelog. Abortando commit."
  exit 0
fi

git commit -m "chore(release): $NEW_VERSION"
git tag "$NEW_VERSION"

git push origin main
git push origin "$NEW_VERSION"