name: Slim Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Permite criar tags/releases

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'

      - name: Run Tag & Release Script
        run: |
          chmod +x scripts/tag-and-release.sh
          ./scripts/tag-and-release.sh