name: Slim Release
 
 on:
   push:
     branches:
       - main
 
 jobs:
   release:
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout
         uses: actions/checkout@v4
         with:
           token: ${{ secrets.GITHUB_TOKEN }}  # permite push/tag
 
       - name: Setup Git
         run: |
           git config --global user.name 'github-actions'
           git config --global user.email 'actions@github.com'
 
       - name: Run Tag & Release Script
   
         run: |
           chmod +x scripts/tag-and-release.sh
           ./scripts/tag-and-release.sh